# Generated by Django 5.0.6 on 2024-09-02 15:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitionername', models.CharField(max_length=100)),
                ('petitioneraddr', models.TextField()),
                ('petitionercontact_no', models.CharField(max_length=12)),
                ('aadharno', models.CharField(max_length=20)),
                ('case', models.CharField(max_length=5000)),
                ('casedetails', models.TextField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('fir', models.FileField(null=True, upload_to='fir/')),
            ],
        ),
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policestation',
            fields=[
                ('stationid', models.IntegerField(primary_key=True, serialize=False)),
                ('stationname', models.CharField(max_length=200)),
                ('addr1', models.CharField(max_length=200)),
                ('addr2', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='', max_length=25)),
                ('city', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('approve', models.IntegerField(default=0)),
                ('usertype', models.CharField(default='station', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Publicuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='public', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('DGP & SPC', 'Director General of Police & State Police Chief (DGP & SPC)'), ('ADGP', 'Additional Director General of Police (ADGP)'), ('IG', 'Inspector General of Police (IG)'), ('DIG', 'Deputy Inspector General of Police (DIG)'), ('SP (Selection Grade)', 'Superintendent of Police (Selection Grade) (SP(SG))'), ('SP', 'Superintendent of Police (SP)'), ('Addl.SP', 'Additional Superintendent of Police (Addl.SP)'), ('ASP', 'Assistant Superintendent of Police (ASP) [IPS]'), ('ASP(Probationary Rank: 2 years of service)', 'Assistant Superintendent of Police (Probationary Rank: 2 years of service)(ASP) [IPS Trainee]'), ('ASP(Probationary Rank: 1 year of service)', 'Assistant Superintendent of Police (Probationary Rank: 1 year of service)(ASP) [IPS Trainee]'), ('DYSP', 'Deputy Superintendent of Police (DYSP) [KPS]'), ('IP', 'Inspector of Police (IP)'), ('SI', 'Sub-Inspector of Police (SI)'), ('ASI', 'Assistant Sub-Inspector of Police (ASI)'), ('SCPO', 'Head constable/Senior Civil Police Officer (SCPO)'), ('CPO', 'Constable/Civil Police Officer (CPO)')], max_length=100)),
                ('basic_salary', models.FloatField(default=0)),
                ('HRA', models.FloatField(default=0)),
                ('DA', models.FloatField(default=0)),
                ('PF', models.FloatField(default=0)),
                ('total_salary', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('crimedetails', models.TextField()),
                ('image', models.FileField(upload_to='images/')),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('stationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='Publiccase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharno', models.CharField(max_length=20)),
                ('petitioneraddr', models.TextField()),
                ('case', models.CharField(max_length=5000)),
                ('casedetails', models.TextField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('status', models.TextField(default='Pending')),
                ('fir', models.FileField(null=True, upload_to='fir/')),
                ('stationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.policestation')),
                ('publicid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('FIR_No', models.AutoField(primary_key=True, serialize=False)),
                ('court', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('PSname', models.CharField(max_length=100)),
                ('date_of_case_given', models.DateField()),
                ('Act', models.CharField(max_length=1000)),
                ('Sections', models.CharField(max_length=100)),
                ('date_of_crime', models.DateField()),
                ('location', models.TextField()),
                ('Petitioner_name', models.CharField(max_length=100)),
                ('Details_of_known_Suspected', models.TextField()),
                ('Case_description', models.TextField()),
                ('caseid2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fir_cases', to='theusers.case')),
                ('caseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fir_cases', to='theusers.publiccase')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5000)),
                ('complaint', models.TextField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(default='Pending')),
                ('pcaseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.publiccase')),
                ('publicid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='Stationstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='D.O.B')),
                ('designation', models.CharField(choices=[('DGP & SPC', 'Director General of Police & State Police Chief (DGP & SPC)'), ('ADGP', 'Additional Director General of Police (ADGP)'), ('IG', 'Inspector General of Police (IG)'), ('DIG', 'Deputy Inspector General of Police (DIG)'), ('SP (Selection Grade)', 'Superintendent of Police (Selection Grade) (SP(SG))'), ('SP', 'Superintendent of Police (SP)'), ('Addl.SP', 'Additional Superintendent of Police (Addl.SP)'), ('ASP', 'Assistant Superintendent of Police (ASP) [IPS]'), ('ASP(Probationary Rank: 2 years of service)', 'Assistant Superintendent of Police (Probationary Rank: 2 years of service)(ASP) [IPS Trainee]'), ('ASP(Probationary Rank: 1 year of service)', 'Assistant Superintendent of Police (Probationary Rank: 1 year of service)(ASP) [IPS Trainee]'), ('DYSP', 'Deputy Superintendent of Police (DYSP) [KPS]'), ('IP', 'Inspector of Police (IP)'), ('SI', 'Sub-Inspector of Police (SI)'), ('ASI', 'Assistant Sub-Inspector of Police (ASI)'), ('SCPO', 'Head constable/Senior Civil Police Officer (SCPO)'), ('CPO', 'Constable/Civil Police Officer (CPO)')], max_length=100)),
                ('policestation', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('approve', models.IntegerField(default=0)),
                ('usertype', models.CharField(default='staff', max_length=25)),
                ('work_history', models.FileField(null=True, upload_to='work_history/')),
                ('stationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='Staffduty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('duty', models.CharField(max_length=5000)),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('stationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.policestation')),
                ('staffid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.stationstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Staffchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('recieverid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.publicuser')),
                ('senderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.stationstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Publicchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('senderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.publicuser')),
                ('recieverid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.stationstaff')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='staffid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.stationstaff'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(default='Absent', max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('stationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.policestation')),
                ('staffid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theusers.stationstaff')),
            ],
        ),
    ]
