# Generated by Django 5.0.6 on 2024-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='petitionercontact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stationstaff',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
