# Generated by Django 5.0.6 on 2024-09-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theusers', '0003_alter_case_aadharno_alter_publiccase_aadharno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
